# Generated by Django 3.2.5 on 2021-07-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='poster_path',
        ),
    ]
