# Generated by Django 3.2.5 on 2021-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0003_alter_movie_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
